### ISSUE TITLE
Restoring detailed list

### ISSUE THREAD

**Issue by ttamminen** [TimboKZ/Chonky#24]
I am migrating from 0.x version to the 1.x, and I could not find the detailed list from the 0.x version.

Anyone working on this? If no one is working on it, then I might take a look. 

I am not 100% certain if I should write my custom version or add it to the core, as the requirements I have it for later are quite specific.

**Comment by TimboKZ** [comment]
Hi, this feature is in my backlog. I'm planning to work on it this weekend.

About custom implementation - I think the best course of action is to wait for this feature to be added to Chonky's built-in `FileList`. Then, if the provided implementation does not match your requirements, you can create a custom component based on Chonky's `FileList`.

**Comment by TimboKZ** [comment]
I have just released Chonky v1.1.1, which includes support for _List_ and _File_ views. See  [relevant documentation section](https://timbokz.github.io/Chonky/1.x/?path=/docs/basics-specifying-default-file-view--file-view-example).

If there are no problems with the new features, I will close this ticket in a few days.

**Comment by ttamminen** [comment]
Great work, @TimboKZ ! 

I changed the default view to the Details and it worked like documented. 

I want to remove the Grid and Details buttons, but for some reason, the control buttons are always visible even though those are not configured to be shown:

```
  const fileActions = [
    ChonkyActions.CreateFolder,
    ChonkyActions.DeleteFiles,
    ChonkyActions.DownloadFiles,
    ChonkyActions.OpenParentFolder,
    ChonkyActions.UploadFiles
  ]
```

To those who upgrade to the latest version: `fillParentContainer` prop doesn't exist anymore, so it can be removed without problems.

**Comment by TimboKZ** [comment]
List and Grid buttons still appear in the toolbar because they are [a part of `DefaultFileActions`](https://timbokz.github.io/Chonky/1.x/?path=/docs/api-reference-built-in-file-actions--page). If you just want the buttons to disappear from the toolbar, the best way to do it is to override the config of relevant actions:

```ts
import 'chonky/style/main.css';
import { ChonkyActions, FileBrowser } from 'chonky';

(ChonkyActions.EnableListView.toolbarButton as any) = undefined;
(ChonkyActions.EnableGridView.toolbarButton as any) = undefined;

export const MyComponent = () => { /* ... */ };
```

There's also another way that involves disabling all default file actions and re-enabling the relevant ones by hand. I wouldn't recommend this because it compromises the forward-compatibility of your project with future versions of Chonky.

P.S. Good catch with `fillParentContainer`, I'll update the changelog to mention it.
