### ISSUE TITLE
What is the default file order?

### ISSUE THREAD

**Issue by Sultan-Mohammad** [TimboKZ/Chonky#33]
What is the default file order? Shouldn't be as same as the supplied array? Seems like when the file browser renders the files, it shuffles the array elements in random order. Also, how can I get the file sort action types(ascending, descending, etc. )?

**Comment by TimboKZ** [comment]
[By default](https://github.com/TimboKZ/Chonky/blob/b1a564605fe2a0073aef9157e97d376e24c75fca/src/recoil/sort.recoil.ts#L10-L14), files are sorted by name in ascending order.

Custom file sorting is supported, but unfortunately note documented. You can create file sorting actions based on existing built-in sorting actions:
https://github.com/TimboKZ/Chonky/blob/b1a564605fe2a0073aef9157e97d376e24c75fca/src/util/file-actions-definitions.ts#L107-L135

Can you tell me a bit more about your use case? Do you sort files in some special way that is not covered by built-in file sorting actions?

It is worth noting that there is currently no feature to set the default file sorting, nor disable file sorting. For the latter, you could create a custom file action that will return the same comparator value for all items (e.g. `null`) to achieve the same affect, but I realise that this is not ideal.

**Comment by Sultan-Mohammad** [comment]
When I sort file (by name, date modified, etc.) files are sorted in the front end, I need to sort that in the server too. I can catch the file action by the handler, then I can call my API. But the file action handler doesn't provide the sorting type info(ascending or descending). How I can get the sorting type?

**Comment by TimboKZ** [comment]
Whenever a new sorting action is triggered (e.g. the current sort order is by name, and then users wants to sort by date), Chonky sets the sorting order to ascending:
https://github.com/TimboKZ/Chonky/blob/b1a564605fe2a0073aef9157e97d376e24c75fca/src/util/file-action-handlers.ts#L130-L132

When the user activates the same sorting action again, Chonky just toggles between ascending and descending orders.

For your purposes, you can track the `prevSortActionId` and `newSortActionId`, where `prevSortActionId` is initially set to `ChonkyActions.SortFilesByName.id`. 

When a new sorting action is triggered, if `newSortActionId != prevSortActionId`, you know that the sort order will be ascending. Otherwise, it will be descending.

I realise this is a hacky solution, but at the moment this is the only option you have that doesn't involve forking Chonky or writing custom components with [Recoil](https://recoiljs.org/).

**Comment by Sultan-Mohammad** [comment]
I thought kind of a similar way, I just wanted to know if Chonky provides any property to catch sort order. However, thanks a lot for your prompt responses.
