### ISSUE TITLE
ShowHiddenFiles, ShowFolderFirst,... default option value configurable?

### ISSUE THREAD

**Issue by aschuma** [TimboKZ/Chonky#34]
How can set an initial value for the _standard_ menu options _ShowHiddenFiles, ShowFolderFirst_ ?

**Comment by TimboKZ** [comment]
At the moment this is not supported, but there are plans to add this feature.

Does it significantly affect your use case?

**Comment by aschuma** [comment]
Thank you for your prompt reply.

This feature would be helpful. I have to present the content of some AWS S3 buckets which are placed in a bunch of tabs.

I could try it my self, but I am not a React/JS expert at all.

What starting point would you suggest?

**Comment by TimboKZ** [comment]
My bad. This will sound embarrassing because I'm the author of the library, but your use case is actually supported - I completely forgot I implemented this feature.

You can easily set the default value for options by changing the `ChonkyActions.<Action>.option.defaultValue` directly. For example, if you want hidden files to be hidden by default, you could do:

```typescript
import { ChonkyActions } from 'chonky';

ChonkyActions.ToggleHiddenFiles.option.defaultValue = false;
```

Here are the definitions for built-in options:

https://github.com/TimboKZ/Chonky/blob/b1a564605fe2a0073aef9157e97d376e24c75fca/src/util/file-actions-definitions.ts#L138-L162

**Comment by aschuma** [comment]
You have pointing me in the right direction.

Thank you very much for your help and for providing this great piece of software, I appreciate that very much.

**Comment by universalhandle** [comment]
In TypeScript, setting the `defaultValue` as described yields an error:

`Cannot assign to 'defaultValue' because it is a read-only property`

Any other suggestions? To be clear, what I'm looking to do is allow the user to show hidden files but hide them initially by default.

Thanks!

**Comment by TimboKZ** [comment]
Hi, I suggest you cast the parent object to `any` or create a writeable
deepcopy of the built-in action.

**Comment by universalhandle** [comment]
For what it's worth, it does work to do:

```ts
// @ts-ignore
ChonkyActions.ToggleHiddenFiles.option.defaultValue = false;
```

I don't love it, but it's good enough for my current hackathon project.

Thanks for writing back.

**Comment by universalhandle** [comment]
If the desire _is_ for users to be able to interact with the defaults this way, then I think it would just be a matter of changing the interface so that the property isn't `readonly`. (Caveat: I've looked at the code only cursorily.)

**Comment by TimboKZ** [comment]
You are absolutely right, the built-in actions are read only because they
are not meant to be changed.

Chonky allows users to formally override built-in actions by providing a
custom action with the same action ID. This the proper way to make this
change is to deepcopy the entire built-in file action object, change some
fields as appropriate, and pass in your new action to Chonky via
fileActions prop.

That said, disabling TS checks & overwriting the field directly works
perfectly well in 99.99% of cases, so I have no problem with people doing
that.
