### ISSUE TITLE
Custom date format

### ISSUE THREAD

**Issue by toktaktk** [TimboKZ/Chonky#37]
it there any chance where can I custom date format .What I found right now is  "d mmmm, HH:MM", "d mmmm yyyy, HH:MM"  and timeAgo

**Comment by TimboKZ** [comment]
Hi, at the moment the only way to customise the date is to fork Chonky and change the library source code directly.

I am currently working on the 2.x release, which will include a feature to change the date format. It will come out in the next few weeks.

**Comment by toktaktk** [comment]
Well, thank you TimboKZ for creating this I'm a big fan of your since 0.x version and I still using it the legacy.

**Comment by TimboKZ** [comment]
You're welcome!

Out of curiosity, why do you use the legacy version? Does the React version you are on not support hooks?

**Comment by toktaktk** [comment]
I'm looking forward to 2.x v too ^^

**Comment by AndreyVanyakin** [comment]
Hi@TimboKZ . Enjoying the v2, it rocks !

Is the custom date format is something you are still looking at (and do you have any ETA, just to get an idea should I fork now) ?

There's one other thing I noticed which you may want to know about. These two seem to cross mixed
![image](https://user-images.githubusercontent.com/38654357/101285346-ae8e2b00-37f5-11eb-8881-41914d34176a.png)

Thanks for keeping this project up
Cheers, Andrey

**Comment by TimboKZ** [comment]
Hi @AndreyVanyakin, you're absolutely right about the variables - that's a bug.

I am currently working on adding i18n support to Chonky using `react-intl` library. As I understand, `react-intl` lets you provide [custom formatters](https://formatjs.io/docs/react-intl/api#formatdate) for a bunch of things, including dates. If that works out, Chonky should get custom date format feature for free when i18n is released. Otherwise, it will be the next thing on my todo list.

**Comment by TimboKZ** [comment]
Hi @toktaktk, @AndreyVanyakin, I have just released v2.1.0 that adds i18n support, and by extension supports custom date formats.

You can see the demo here:

https://chonky.io/storybook/2.x/?path=/story/file-browser-demos--localization

**Comment by AndreyVanyakin** [comment]
@TimboKZ  That was just wow, very fast. Thanks a lot, will check it right away
