### ISSUE TITLE
move items to any folders in any levels

### ISSUE THREAD

**Issue by nimblemo** [TimboKZ/Chonky#42]
The good idea make possible move files or folders in any levels through context menu item with tree view folders structure . It need because in current version chonky allow move files and folders in only same level folders. The second idea is move files and folders through breadcrumbs menu when drag file or folder on breadcrumb level

**Comment by TimboKZ** [comment]
Hi, thanks for the suggestions, I agree with both of them. I actually briefly tried to implement it before, but the drag & drop code was too much of a mess.

Chonky 2.x does some refactoring around file entry components which makes supporting the features you suggest much easier.

I'll get on this once other todos from #40 are completed.

**Comment by nimblemo** [comment]
thanks a lot :)

**Comment by wraybowling** [comment]
I second that drop onto breadcrumb would be ideal for the elements that currently exist. A tree sidebar that you could drop to would also be good.

**Comment by TimboKZ** [comment]
I have just released [Chonky v2.0.3](https://github.com/TimboKZ/Chonky/releases/tag/chonky%402.0.2), that implements the features mentioned in this issue. It also lets users define custom drop zones, as shows in the [_Advanced drag & drop_](https://chonky.io/storybook/2.x/?path=/story/file-browser-demos--advanced-dnd) example.

There is currently one _visual_ bug - when you use drag & drop hover to open an empty folder, a folder-wide DnD indicator does not show up (even though you can drop files into the folder). I believe this might be a bug in `react-dnd`, I'll create an issue in their repo. I'll probably keep this issue open until this bug is resolved.

Quick preview:

![Chonky DND open preview](https://user-images.githubusercontent.com/5504588/99171387-846ab100-2700-11eb-9106-ae9e7299c6a4.gif)
