### ISSUE TITLE
Duplicate change selection dispatched events

### ISSUE THREAD

**Issue by alexisdurieux** [TimboKZ/Chonky#73]
Hello,

I am trying to customize the click behaviour of the file browser. 
I want the single click to toggle the file selection and a double click to trigger a download or to dive in a folder.
I am having the following code in `onFileAction`:
```js
case 'mouse_click_file': {
    const mouseClickFilePayload: MouseClickFilePayload = action.payload as MouseClickFilePayload;
    switch (mouseClickFilePayload.clickType) {
        case 'single': {
            if (ref && ref.current) {
                const selectedFiles = ref.current.getFileSelection();
                const fileId = mouseClickFilePayload.file.id;
                if (selectedFiles.has(fileId)) {
                    selectedFiles.delete(fileId);
                    ref.current.setFileSelection(selectedFiles);
                } else {
                    ref.current.setFileSelection(selectedFiles.add(fileId))
                }
            }
            break;
        }
        case 'double': {
            if (mouseClickFilePayload.file.isDir) {
                const fileId = mouseClickFilePayload.file.id;
                this.fetchFiles([], fileId);
            }
            break;
        }
        default:
            break;
    }
    
    break;
  }
```
However after the click a first event is triggered with the correct selected file. But then another change selection event is dispatched with an empty set. So the selected files can't be stack.

Should I change my approach or is there a bug ?

Thank you in advance for your help !

**Comment by TimboKZ** [comment]
Hey @alexisdurieux, this might indeed indicate a bug, but I would also suggest trying a different approach - you can re-define the internal Chonky action effects to make single click toggle the selection on a file instead of doing an exclusive selection.

Setting `exclusive: false` on line 94 below should achieve what you want. 
https://github.com/TimboKZ/Chonky/blob/ee9809e2dfa66c4eae56c89b6152d6d2709bdd50/packages/chonky/src/action-definitions/essential.ts#L89-L103

**Comment by alexisdurieux** [comment]
Thank you for your feedback @TimboKZ
