### ISSUE TITLE
Roadmap to 1.0?

### ISSUE THREAD

**Issue by baleeds** [TimboKZ/Chonky#8]
What features are you looking to implement before you feel ready to release a version 1.0 and lock down the API?

We would like to use Chonky in production, and there are some features we would like to implement before it's ready for our use.

Some things that we would like to see (and are willing to contribute):
- Rename files and folders
- Ability to add custom action buttons next to create/delete/etc
- Drag and drop to move files

**Comment by TimboKZ** [comment]
All of the above plus:
* Support for custom file entry components (or at least wrappers), so it's easier to connect libraries like [https://www.npmjs.com/package/react-context-menu-wrapper](react-context-menu-wrapper).
* Better support for custom actions, so things like cutting/pasting files can be implemented externally without dirty hacks.
* File search/filter - just a small text box inside the `Controls` component that will (efficiently) filter file entries by name/meta data.

Before that, however, I'd like to add some tests, and making the whole thing nicely testable would require some refactoring of the overall architecture.

Getting any of these things done will require considerable effort. I'm a bit busy with my day job at the moment so I can't spend much time on them. If you think your team can implement some of these features, I'll be happy to walk you through the architecture and brainstorm ideas with you.

What I can say is that I **will** get back to Chonky at some point as it's the main dependency of [a different project](https://github.com/TimboKZ/Ogma). This also means I have some basic requirements that Chonky should fulfil, but we seem to agree on those. Unfortunately I can't make any promises on my availability so it's best you start without me if you will end up adding something.

**Comment by TimboKZ** [comment]
About locking down the API - not sure if the current API is fully fit for purpose. For my personal use cases, *support for custom file entry components* is the only feature that is missing. Once I get that done, I'll check if any improvements can be made to the existing API.

That said, I think any changes I can make will be backwards compatible, and I will just mark the old interface as deprecated.

**Comment by baleeds** [comment]
Okay, it sounds like the first step is making the refactors you mention, and then getting some tests up and running.  What did you have in mind?

**Comment by baleeds** [comment]
Also, are you open to using hooks?  If so, we'll need to upgrade to 16.8.  Are you okay with the presence of `UNSAFE_componentWillReceiveProps()`?

**Comment by TimboKZ** [comment]
**Re: Refactoring** - I'll need to look at the code again since I haven't touched it in a bit and I didn't note down the changes anywhere. Below I include some suggestions off the top of my head.

I'm definitely up for hooks, in fact most of the refactoring I had in mind is centred around hooks. Bumping peer dependencies to 16.8 sounds good also.

Not very happy about `UNSAFE_componentWillReceiveProps()`, I think it needs to go. **(1)** I think this (and many other problems) can be solved by having a more intelligent internal state management system, most likely something Redux-style with `useDispatch` and various selectors. This would make the code around selections, cutting/pasting, sorting files and others much cleaner and easier to test.

**(2)** The other problem is handling clicks and key presses. I'm not sure if you had a chance to dive deep into that part, but there's a lot of different listeners on different levels (some live in FileBrowser, some in FileEntry, some in Util). I think these interactions would be easier to test if user input was a separate module. Having this logic abstracted away can also make it easier to support triggering custom actions using the keyboard.

I think replacing the `FileBrowser` with a functional component and breaking out all of the logic into separate hooks is the way to go, but that will take some time.

**Comment by TimboKZ** [comment]
Worth mentioning here that #9 addresses some of these points.

**Comment by TimboKZ** [comment]
Hello, FYI the upcoming `1.0` release of Chonky includes most of the features you requested in the original issue:
https://timbokz.github.io/Chonky/1.x/

If you are still using Chonky and want to request some changes to the API or features, now would be a good time.

**Comment by TimboKZ** [comment]
Version 1.0 is now released, closing this ticket.
